### ISSUE TITLE
Moar tables needed for network sites

### ISSUE THREAD

**Issue by richplane** [castlegateit/cgit-wp-security-tool#7]
The cgit_security_logins table is only created once on a network site; the prefix will be different for every site so it will be attempting to write to multiple nonexistent tables. It either needs a site_id adding to the table or (more complicatedly) need to create (and then synchronise) a table for each site in the network.

**Comment by johnkhughes** [comment]
Fixed in version 2.5, although we'll need to reactivate the plugin for the database changes to take effect.
